name: smart_psu_hp_doctor
description: App BLE monitor untuk Smart Power Supply pendeteksi kerusakan HP
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.35.10
  fl_chart: ^0.68.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
